# Generated by Django 3.0.7 on 2020-06-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_pl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='npcinfo',
            name='details',
            field=models.CharField(default='', max_length=512),
        ),
    ]
